sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sidhantborade007/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sidhantborade007/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Elastic_Beanstalk_Application"
  env: "ElasticBeanstalkApplication-env"
  bucket_name: "elasticbeanstalk-eu-north-1-111313316382"
  bucket_path: "Elastic_Beanstalk_Application"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
